version: '3'
services:
  app_php:
    container_name: app_php
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    networks:
      - app-network
    user: "1000:1000"
  app_nginx:
    image: nginx:latest
    container_name: app_nginx
    volumes:
    - ./:/var/www
    - ./docker/nginx/:/etc/nginx/conf.d
    ports:
    - "8181:80"
    - "1433:433"
    networks:
      - app-network
  app_mysql:
    image: mysql:5.7.24
    container_name: app_mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: 1
      command: mysqld --sql_mode="STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION" --max-allowed-packet=15000000
    volumes:
      - dbmysql:/var/lib/mysql/
    networks:
      - app-network
    ports:
      - "33310:3306"


networks:
  app-network:
    driver: bridge

volumes:
  dbmysql:
    driver: local